# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ultrasound_with_gesture.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ultrasound_with_gesture.proto',
  package='tutorial',
  syntax='proto2',
  serialized_pb=_b('\n\x1dultrasound_with_gesture.proto\x12\x08tutorial\"\xce\x04\n\x0fUltrasoundVideo\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x44\n\x11ultrasound_images\x18\x02 \x03(\x0b\x32).tutorial.UltrasoundVideo.UltrasoundImage\x1a\xe6\x03\n\x0fUltrasoundImage\x12\x12\n\x06pixels\x18\x01 \x03(\x05\x42\x02\x10\x01\x12\x0c\n\x04rows\x18\x02 \x02(\r\x12\x0c\n\x04\x63ols\x18\x03 \x02(\r\x12\x42\n\x07gesture\x18\x04 \x01(\x0b\x32\x31.tutorial.UltrasoundVideo.UltrasoundImage.Gesture\x12\x11\n\ttimestamp\x18\x05 \x02(\x02\x1a\xcb\x02\n\x07Gesture\x12\x12\n\nthumb_bend\x18\x01 \x02(\x02\x12\x12\n\nindex_bend\x18\x02 \x02(\x02\x12\x13\n\x0bmiddle_bend\x18\x03 \x02(\x02\x12\x11\n\tring_bend\x18\x04 \x02(\x02\x12\x12\n\npinky_bend\x18\x05 \x02(\x02\x12\x13\n\x0bthumb_press\x18\x06 \x02(\x02\x12\x13\n\x0bindex_press\x18\x07 \x02(\x02\x12\x14\n\x0cmiddle_press\x18\x08 \x02(\x02\x12\x12\n\nring_press\x18\t \x02(\x02\x12\x13\n\x0bpinky_press\x18\n \x02(\x02\x12\x12\n\nwrist_roll\x18\x0b \x02(\x02\x12\x13\n\x0bwrist_pitch\x18\x0c \x02(\x02\x12\x11\n\twrist_yaw\x18\r \x02(\x02\x12\x11\n\thand_roll\x18\x0e \x02(\x02\x12\x12\n\nhand_pitch\x18\x0f \x02(\x02\x12\x10\n\x08hand_yaw\x18\x10 \x02(\x02')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_ULTRASOUNDVIDEO_ULTRASOUNDIMAGE_GESTURE = _descriptor.Descriptor(
  name='Gesture',
  full_name='tutorial.UltrasoundVideo.UltrasoundImage.Gesture',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='thumb_bend', full_name='tutorial.UltrasoundVideo.UltrasoundImage.Gesture.thumb_bend', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='index_bend', full_name='tutorial.UltrasoundVideo.UltrasoundImage.Gesture.index_bend', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='middle_bend', full_name='tutorial.UltrasoundVideo.UltrasoundImage.Gesture.middle_bend', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ring_bend', full_name='tutorial.UltrasoundVideo.UltrasoundImage.Gesture.ring_bend', index=3,
      number=4, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pinky_bend', full_name='tutorial.UltrasoundVideo.UltrasoundImage.Gesture.pinky_bend', index=4,
      number=5, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='thumb_press', full_name='tutorial.UltrasoundVideo.UltrasoundImage.Gesture.thumb_press', index=5,
      number=6, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='index_press', full_name='tutorial.UltrasoundVideo.UltrasoundImage.Gesture.index_press', index=6,
      number=7, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='middle_press', full_name='tutorial.UltrasoundVideo.UltrasoundImage.Gesture.middle_press', index=7,
      number=8, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ring_press', full_name='tutorial.UltrasoundVideo.UltrasoundImage.Gesture.ring_press', index=8,
      number=9, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pinky_press', full_name='tutorial.UltrasoundVideo.UltrasoundImage.Gesture.pinky_press', index=9,
      number=10, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='wrist_roll', full_name='tutorial.UltrasoundVideo.UltrasoundImage.Gesture.wrist_roll', index=10,
      number=11, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='wrist_pitch', full_name='tutorial.UltrasoundVideo.UltrasoundImage.Gesture.wrist_pitch', index=11,
      number=12, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='wrist_yaw', full_name='tutorial.UltrasoundVideo.UltrasoundImage.Gesture.wrist_yaw', index=12,
      number=13, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hand_roll', full_name='tutorial.UltrasoundVideo.UltrasoundImage.Gesture.hand_roll', index=13,
      number=14, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hand_pitch', full_name='tutorial.UltrasoundVideo.UltrasoundImage.Gesture.hand_pitch', index=14,
      number=15, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hand_yaw', full_name='tutorial.UltrasoundVideo.UltrasoundImage.Gesture.hand_yaw', index=15,
      number=16, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=303,
  serialized_end=634,
)

_ULTRASOUNDVIDEO_ULTRASOUNDIMAGE = _descriptor.Descriptor(
  name='UltrasoundImage',
  full_name='tutorial.UltrasoundVideo.UltrasoundImage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pixels', full_name='tutorial.UltrasoundVideo.UltrasoundImage.pixels', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))),
    _descriptor.FieldDescriptor(
      name='rows', full_name='tutorial.UltrasoundVideo.UltrasoundImage.rows', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cols', full_name='tutorial.UltrasoundVideo.UltrasoundImage.cols', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gesture', full_name='tutorial.UltrasoundVideo.UltrasoundImage.gesture', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='tutorial.UltrasoundVideo.UltrasoundImage.timestamp', index=4,
      number=5, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_ULTRASOUNDVIDEO_ULTRASOUNDIMAGE_GESTURE, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=148,
  serialized_end=634,
)

_ULTRASOUNDVIDEO = _descriptor.Descriptor(
  name='UltrasoundVideo',
  full_name='tutorial.UltrasoundVideo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='tutorial.UltrasoundVideo.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ultrasound_images', full_name='tutorial.UltrasoundVideo.ultrasound_images', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_ULTRASOUNDVIDEO_ULTRASOUNDIMAGE, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=634,
)

_ULTRASOUNDVIDEO_ULTRASOUNDIMAGE_GESTURE.containing_type = _ULTRASOUNDVIDEO_ULTRASOUNDIMAGE
_ULTRASOUNDVIDEO_ULTRASOUNDIMAGE.fields_by_name['gesture'].message_type = _ULTRASOUNDVIDEO_ULTRASOUNDIMAGE_GESTURE
_ULTRASOUNDVIDEO_ULTRASOUNDIMAGE.containing_type = _ULTRASOUNDVIDEO
_ULTRASOUNDVIDEO.fields_by_name['ultrasound_images'].message_type = _ULTRASOUNDVIDEO_ULTRASOUNDIMAGE
DESCRIPTOR.message_types_by_name['UltrasoundVideo'] = _ULTRASOUNDVIDEO

UltrasoundVideo = _reflection.GeneratedProtocolMessageType('UltrasoundVideo', (_message.Message,), dict(

  UltrasoundImage = _reflection.GeneratedProtocolMessageType('UltrasoundImage', (_message.Message,), dict(

    Gesture = _reflection.GeneratedProtocolMessageType('Gesture', (_message.Message,), dict(
      DESCRIPTOR = _ULTRASOUNDVIDEO_ULTRASOUNDIMAGE_GESTURE,
      __module__ = 'ultrasound_with_gesture_pb2'
      # @@protoc_insertion_point(class_scope:tutorial.UltrasoundVideo.UltrasoundImage.Gesture)
      ))
    ,
    DESCRIPTOR = _ULTRASOUNDVIDEO_ULTRASOUNDIMAGE,
    __module__ = 'ultrasound_with_gesture_pb2'
    # @@protoc_insertion_point(class_scope:tutorial.UltrasoundVideo.UltrasoundImage)
    ))
  ,
  DESCRIPTOR = _ULTRASOUNDVIDEO,
  __module__ = 'ultrasound_with_gesture_pb2'
  # @@protoc_insertion_point(class_scope:tutorial.UltrasoundVideo)
  ))
_sym_db.RegisterMessage(UltrasoundVideo)
_sym_db.RegisterMessage(UltrasoundVideo.UltrasoundImage)
_sym_db.RegisterMessage(UltrasoundVideo.UltrasoundImage.Gesture)


_ULTRASOUNDVIDEO_ULTRASOUNDIMAGE.fields_by_name['pixels'].has_options = True
_ULTRASOUNDVIDEO_ULTRASOUNDIMAGE.fields_by_name['pixels']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))
# @@protoc_insertion_point(module_scope)
